[options]
db_host = localhost
db_port = 5432
db_user = odoo
db_password = 123456
admin_passwd = $pbkdf2-sha512$600000$ulfK2dv7fy/F.N9bC2HsPQ$GhUM8LaxRhUXXun7KSHbVR9KIQtsQPx7qEx6MNs2Vu3t4cBwspwxgVacVODVTJeujFgzDUcJQnZPi1KlcU5feA

